### ISSUE TITLE
Unrecognized arguments in  RWKV_LoRA.ipynb

### ISSUE THREAD

**Issue by predtech1988** [resloved/RWKV-notebooks#2]
Hi. There is mismatch in arguments in notebook and train.py causing an error "train.py: error: unrecognized arguments: --lora-r 8 --lora-alpha 32 --lora-dropout 0.01".  

In RWKV_LoRA.ipynb Training session there is arguments --lora --lora-r 8 --lora-alpha 32 --lora-dropout 0.01 
But in https://github.com/Blealtan/RWKV-LM-LoRA/blob/main/RWKV-v4neo/train.py this argument keys are: --lora_r, --lora_alpha, --lora_dropout.

**Comment by resloved** [comment]
Looks like they changed the formatting for the arguments after I had written the notebook (Related commit https://github.com/Blealtan/RWKV-LM-LoRA/commit/c2ca2d5c8776b1eefcd2affbaf9bc42bf3f574a5)

Should be a quick fix

**Comment by resloved** [comment]
Should be fixed as of https://github.com/resloved/RWKV-notebooks/commit/f619ad1028b375f84f856914613eb64a627c1a4f
